import sqlite3
import tempfile
import unittest
from pathlib import Path

from emociones import cuentas
from emociones.bd import BaseDeDatos
from emociones.config import Configuracion
from tests.utiles import URL_POSTGRES, nueva_bd

# La base como la dejaba la versión con un solo dueño (antes de las cuentas).
ESQUEMA_VIEJO = """
CREATE TABLE registros (id {id}, creado_en {entero} NOT NULL, causa TEXT, mensaje TEXT, chat_id {entero});
CREATE TABLE registro_emociones (id {id}, registro_id {entero} NOT NULL REFERENCES registros(id) ON DELETE CASCADE,
                                 palabra TEXT NOT NULL, emocion TEXT);
CREATE TABLE palabras_aprendidas (palabra TEXT PRIMARY KEY, emocion TEXT NOT NULL);
CREATE TABLE ajustes (clave TEXT PRIMARY KEY, valor TEXT);
CREATE TABLE esperas (chat_id {entero} PRIMARY KEY, registro_id {entero} NOT NULL REFERENCES registros(id)
                      ON DELETE CASCADE, vence {entero} NOT NULL);
CREATE TABLE accesos (correo TEXT PRIMARY KEY, creado_en {entero} NOT NULL);
INSERT INTO registros (creado_en, causa, mensaje, chat_id) VALUES (1000, 'Llueve', 'triste: llueve', 7);
INSERT INTO registro_emociones (registro_id, palabra, emocion) VALUES (1, 'triste', 'tristeza');
INSERT INTO palabras_aprendidas VALUES ('agotado', 'tristeza/deprimido');
INSERT INTO ajustes VALUES ('dueno', '7');
INSERT INTO accesos VALUES ('psico@gmail.com', 5);
"""

CONFIG = Configuracion(google_id="cliente", google_secreto="secreto", google_correos={"yo@gmail.com"})


def base_vieja(carpeta: str) -> BaseDeDatos:
    """Crea la base con el esquema viejo y la abre con la versión actual (que la migra)."""
    if URL_POSTGRES:
        import psycopg

        with psycopg.connect(URL_POSTGRES, autocommit=True) as con:
            con.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
            con.execute(ESQUEMA_VIEJO.format(id="BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                                             entero="BIGINT"))
        BaseDeDatos._preparadas.discard(URL_POSTGRES)
        return BaseDeDatos(URL_POSTGRES)
    ruta = Path(carpeta) / "vieja.db"
    con = sqlite3.connect(ruta)
    con.executescript(ESQUEMA_VIEJO.format(id="INTEGER PRIMARY KEY AUTOINCREMENT", entero="INTEGER"))
    con.close()
    return BaseDeDatos(ruta)


class TestMigracion(unittest.TestCase):
    def setUp(self):
        self.carpeta = tempfile.TemporaryDirectory()
        self.bd = base_vieja(self.carpeta.name)

    def tearDown(self):
        self.carpeta.cleanup()

    def comprobar_adopcion(self, usuario):
        self.assertEqual(usuario["correo"], "yo@gmail.com")
        self.assertEqual(usuario["telegram_id"], 7)
        [registro] = self.bd.listar_registros(usuario["id"])
        self.assertEqual((registro["causa"], registro["emociones"][0]["emocion"]), ("Llueve", "tristeza"))
        self.assertEqual(self.bd.vocabulario(usuario["id"]), {"agotado": "tristeza/deprimido"})
        self.assertEqual([c["correo"] for c in self.bd.compartidos_de(usuario["id"])], ["psico@gmail.com"])

    def test_al_entrar_con_google_tus_datos_pasan_a_tu_cuenta(self):
        self.comprobar_adopcion(cuentas.usuario_para_correo(self.bd, CONFIG, "yo@gmail.com"))

    def test_o_al_escribirle_al_bot(self):
        self.comprobar_adopcion(cuentas.usuario_para_telegram(self.bd, CONFIG, 7))
        # …y después, al entrar con Google, es la misma cuenta.
        self.assertEqual(cuentas.usuario_para_correo(self.bd, CONFIG, "yo@gmail.com")["telegram_id"], 7)

    def test_la_adopcion_ocurre_una_sola_vez(self):
        yo = cuentas.usuario_para_correo(self.bd, CONFIG, "yo@gmail.com")
        otra = cuentas.usuario_para_correo(self.bd, Configuracion(google_correos={"otra@gmail.com"}), "otra@gmail.com")
        self.assertEqual(self.bd.listar_registros(otra["id"]), [])
        self.assertEqual(len(self.bd.listar_registros(yo["id"])), 1)

    def test_un_desconocido_no_se_queda_con_los_datos(self):
        sin_google = Configuracion()
        self.assertIsNone(cuentas.usuario_para_telegram(self.bd, sin_google, 99))
        self.assertIsNotNone(cuentas.usuario_para_telegram(self.bd, sin_google, 7))

    def test_con_varios_administradores_tus_datos_esperan_a_tu_telegram(self):
        varios = Configuracion(google_id="c", google_secreto="s", google_correos={"yo@gmail.com", "psico@gmail.com"})
        # Si otra persona administradora entra primero, no se queda con tu diario.
        psico = cuentas.usuario_para_correo(self.bd, varios, "psico@gmail.com")
        self.assertEqual(self.bd.listar_registros(psico["id"]), [])
        # Tus datos quedan con tu Telegram…
        con_tu_telegram = cuentas.usuario_para_telegram(self.bd, varios, 7)
        self.assertIsNone(con_tu_telegram["correo"])
        self.assertEqual(len(self.bd.listar_registros(con_tu_telegram["id"])), 1)
        # …y cuando lo vinculas desde tu cuenta de Google, se suman a ella (también los nombres de tu rueda).
        self.bd.renombrar(con_tu_telegram["id"], "enojo", "Bronca")
        yo = cuentas.usuario_para_correo(self.bd, varios, "yo@gmail.com")
        self.assertEqual(cuentas.vincular_telegram(self.bd, yo, 7), "fusionado")
        self.comprobar_adopcion(self.bd.usuario(yo["id"]))
        self.assertEqual(self.bd.nombres(yo["id"]), {"enojo": "Bronca"})
        self.assertIsNone(self.bd.usuario(con_tu_telegram["id"]))

    def test_abrir_dos_veces_no_rompe_nada(self):
        BaseDeDatos._preparadas.discard(self.bd.destino)
        BaseDeDatos(self.bd.destino)  # vuelve a correr la migración sobre la base ya migrada
        self.comprobar_adopcion(cuentas.usuario_para_correo(self.bd, CONFIG, "yo@gmail.com"))


class TestQuienPuedeEntrar(unittest.TestCase):
    def setUp(self):
        self.carpeta = tempfile.TemporaryDirectory()
        self.bd = nueva_bd(self.carpeta.name)

    def tearDown(self):
        self.carpeta.cleanup()

    def test_cualquier_cuenta_de_google_tiene_su_diario(self):
        yo = cuentas.usuario_para_correo(self.bd, CONFIG, "yo@gmail.com")
        nueva = cuentas.usuario_para_correo(self.bd, CONFIG, "nueva@gmail.com")
        self.assertNotEqual(yo["id"], nueva["id"])
        self.assertEqual(cuentas.usuario_para_correo(self.bd, CONFIG, "nueva@gmail.com")["id"], nueva["id"])
        self.assertEqual(self.bd.compartidos_conmigo("nueva@gmail.com"), [])
        # Si le comparten un diario y después se lo dejan de compartir, conserva su cuenta.
        self.bd.compartir(yo["id"], "nueva@gmail.com", 0)
        self.bd.dejar_de_compartir(yo["id"], "nueva@gmail.com")
        self.assertEqual(cuentas.usuario_para_correo(self.bd, CONFIG, "nueva@gmail.com")["id"], nueva["id"])

    def test_en_tu_computadora_el_primero_que_escribe_es_el_dueno(self):
        sin_google = Configuracion()
        self.assertIsNotNone(cuentas.usuario_para_telegram(self.bd, sin_google, 7))
        self.assertIsNone(cuentas.usuario_para_telegram(self.bd, sin_google, 8))

    def test_telegram_usuarios_limita_el_bot(self):
        config = Configuracion(permitidos={8})
        self.assertIsNone(cuentas.usuario_para_telegram(self.bd, config, 7))
        self.assertIsNotNone(cuentas.usuario_para_telegram(self.bd, config, 8))


if __name__ == "__main__":
    unittest.main()
