"""Guardado de registros: SQLite en tu computadora, Postgres (Neon, Supabase…) en Vercel.

Las consultas son las mismas para las dos; solo cambian los tipos de columnas del esquema.
"""

from __future__ import annotations

import sqlite3
import threading
import time
from contextlib import contextmanager
from pathlib import Path

_TABLAS = """
CREATE TABLE IF NOT EXISTS registros (
    id        {id},
    creado_en {entero} NOT NULL,  -- segundos desde 1970 (UTC)
    causa     TEXT,               -- qué lo causó
    mensaje   TEXT,               -- el mensaje original de Telegram
    chat_id   {entero}
);
CREATE TABLE IF NOT EXISTS registro_emociones (
    id          {id},
    registro_id {entero} NOT NULL REFERENCES registros(id) ON DELETE CASCADE,
    palabra     TEXT NOT NULL,    -- como la escribió la persona
    emocion     TEXT              -- id en la rueda; NULL mientras no esté clasificada
);
CREATE INDEX IF NOT EXISTS idx_registros_fecha ON registros(creado_en);
CREATE INDEX IF NOT EXISTS idx_emociones_registro ON registro_emociones(registro_id);
CREATE TABLE IF NOT EXISTS palabras_aprendidas (
    palabra TEXT PRIMARY KEY,     -- normalizada
    emocion TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS ajustes (
    clave TEXT PRIMARY KEY,
    valor TEXT
);
CREATE TABLE IF NOT EXISTS esperas (  -- registros a los que el bot les está pidiendo la causa
    chat_id     {entero} PRIMARY KEY,
    registro_id {entero} NOT NULL REFERENCES registros(id) ON DELETE CASCADE,
    vence       {entero} NOT NULL
);
CREATE TABLE IF NOT EXISTS accesos (  -- cuentas de Google con las que compartiste el panel (solo lectura)
    correo    TEXT PRIMARY KEY,
    creado_en {entero} NOT NULL
);
"""
ESQUEMA_SQLITE = _TABLAS.format(id="INTEGER PRIMARY KEY AUTOINCREMENT", entero="INTEGER")
ESQUEMA_POSTGRES = _TABLAS.format(id="BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", entero="BIGINT")


class _Postgres:
    """Una conexión de psycopg con la forma de sqlite3 (marcadores «?»)."""

    def __init__(self, conexion):
        self._conexion = conexion

    def execute(self, sql: str, parametros: tuple | None = None):
        return self._conexion.execute(sql.replace("?", "%s"), parametros)


class BaseDeDatos:
    """`destino` es la ruta de un archivo SQLite o una URL postgres://…

    Sin `abierta()`, cada operación usa su propia conexión: así el bot y el panel pueden
    usarla a la vez desde hilos distintos.
    """

    _preparadas: set[str] = set()  # destinos cuyo esquema ya se creó en este proceso

    def __init__(self, destino: str | Path):
        texto = self.destino = str(destino)
        self.postgres = texto.startswith(("postgres://", "postgresql://"))
        self._destino = texto if self.postgres else Path(destino)
        self._hilo = threading.local()
        if texto not in BaseDeDatos._preparadas:
            if not self.postgres:
                self._destino.parent.mkdir(parents=True, exist_ok=True)
            with self._abrir() as con:
                if self.postgres:
                    con.execute(ESQUEMA_POSTGRES)
                else:
                    con.executescript(ESQUEMA_SQLITE)
            BaseDeDatos._preparadas.add(texto)

    @contextmanager
    def abierta(self):
        """Usa una sola conexión (y una transacción) para todo el bloque. En Vercel evita
        abrir una conexión nueva a Postgres por cada consulta de un mismo mensaje."""
        if not self.postgres or getattr(self._hilo, "conexion", None) is not None:
            yield
            return
        with self._abrir() as con:
            self._hilo.conexion = con
            try:
                yield
            finally:
                self._hilo.conexion = None

    @contextmanager
    def _conexion(self):
        compartida = getattr(self._hilo, "conexion", None)
        if compartida is not None:
            yield compartida
            return
        with self._abrir() as con:
            yield con

    @contextmanager
    def _abrir(self):
        if self.postgres:
            import psycopg  # solo hace falta en Vercel (requirements.txt)
            from psycopg.rows import dict_row

            # prepare_threshold=None: los «poolers» de Neon/Supabase no conservan sentencias preparadas.
            with psycopg.connect(self._destino, row_factory=dict_row, prepare_threshold=None,
                                 connect_timeout=10) as con:
                yield _Postgres(con)
            return
        con = sqlite3.connect(self._destino, timeout=10)
        con.row_factory = sqlite3.Row
        con.execute("PRAGMA foreign_keys = ON")
        try:
            with con:
                yield con
        finally:
            con.close()

    # --- Registros ---------------------------------------------------------------------

    def crear_registro(self, creado_en: int, causa: str | None, mensaje: str | None,
                       chat_id: int | None, emociones: list[tuple[str, str | None]]) -> tuple[int, list[int]]:
        """Guarda un registro con sus emociones [(palabra, emocion_id o None)]."""
        with self._conexion() as con:
            registro_id = con.execute(
                "INSERT INTO registros (creado_en, causa, mensaje, chat_id) VALUES (?, ?, ?, ?) RETURNING id",
                (creado_en, causa, mensaje, chat_id),
            ).fetchone()["id"]
            fila_ids = [
                con.execute(
                    "INSERT INTO registro_emociones (registro_id, palabra, emocion) VALUES (?, ?, ?) RETURNING id",
                    (registro_id, palabra, emocion),
                ).fetchone()["id"]
                for palabra, emocion in emociones
            ]
        return registro_id, fila_ids

    def agregar_emocion(self, registro_id: int, palabra: str, emocion: str) -> int:
        with self._conexion() as con:
            return con.execute(
                "INSERT INTO registro_emociones (registro_id, palabra, emocion) VALUES (?, ?, ?) RETURNING id",
                (registro_id, palabra, emocion),
            ).fetchone()["id"]

    def clasificar(self, fila_id: int, emocion: str) -> None:
        with self._conexion() as con:
            con.execute("UPDATE registro_emociones SET emocion = ? WHERE id = ?", (emocion, fila_id))

    def obtener_fila(self, fila_id: int) -> dict | None:
        with self._conexion() as con:
            fila = con.execute("SELECT * FROM registro_emociones WHERE id = ?", (fila_id,)).fetchone()
        return dict(fila) if fila else None

    def borrar_fila(self, fila_id: int) -> None:
        with self._conexion() as con:
            con.execute("DELETE FROM registro_emociones WHERE id = ?", (fila_id,))

    def poner_causa(self, registro_id: int, causa: str) -> None:
        with self._conexion() as con:
            con.execute("UPDATE registros SET causa = ? WHERE id = ?", (causa, registro_id))

    def borrar_registro(self, registro_id: int) -> bool:
        with self._conexion() as con:
            return con.execute("DELETE FROM registros WHERE id = ?", (registro_id,)).rowcount > 0

    def obtener_registro(self, registro_id: int) -> dict | None:
        registros = self._leer("WHERE r.id = ?", (registro_id,))
        return registros[0] if registros else None

    def ultimo_registro(self, chat_id: int) -> dict | None:
        with self._conexion() as con:
            fila = con.execute(
                "SELECT id FROM registros WHERE chat_id = ? ORDER BY creado_en DESC, id DESC LIMIT 1",
                (chat_id,),
            ).fetchone()
        return self.obtener_registro(fila["id"]) if fila else None

    def listar_registros(self, desde: int | None = None, hasta: int | None = None) -> list[dict]:
        """Registros del período, del más nuevo al más viejo, cada uno con sus emociones."""
        return self._leer(
            "WHERE r.creado_en >= ? AND r.creado_en < ?",
            (desde if desde is not None else 0, hasta if hasta is not None else 2**62),
        )

    def _leer(self, condicion: str, parametros: tuple) -> list[dict]:
        with self._conexion() as con:
            filas = con.execute(
                f"""SELECT r.id, r.creado_en, r.causa, r.mensaje, r.chat_id,
                           e.id AS fila_id, e.palabra, e.emocion
                    FROM registros r LEFT JOIN registro_emociones e ON e.registro_id = r.id
                    {condicion}
                    ORDER BY r.creado_en DESC, r.id DESC, e.id""",
                parametros,
            ).fetchall()
        registros: dict[int, dict] = {}
        for fila in filas:
            registro = registros.setdefault(fila["id"], {
                "id": fila["id"], "creado_en": fila["creado_en"], "causa": fila["causa"],
                "mensaje": fila["mensaje"], "chat_id": fila["chat_id"], "emociones": [],
            })
            if fila["fila_id"] is not None:
                registro["emociones"].append(
                    {"id": fila["fila_id"], "palabra": fila["palabra"], "emocion": fila["emocion"]}
                )
        return list(registros.values())

    # --- Causa pendiente ---------------------------------------------------------------

    def esperar_causa(self, chat_id: int, registro_id: int, vence: int) -> None:
        with self._conexion() as con:
            con.execute(
                "INSERT INTO esperas (chat_id, registro_id, vence) VALUES (?, ?, ?) "
                "ON CONFLICT(chat_id) DO UPDATE SET registro_id = excluded.registro_id, vence = excluded.vence",
                (chat_id, registro_id, vence),
            )

    def espera(self, chat_id: int) -> int | None:
        """El registro al que le falta la causa, si todavía no venció la espera."""
        with self._conexion() as con:
            fila = con.execute(
                "SELECT registro_id FROM esperas WHERE chat_id = ? AND vence > ?", (chat_id, int(time.time()))
            ).fetchone()
        return fila["registro_id"] if fila else None

    def quitar_espera(self, chat_id: int) -> None:
        with self._conexion() as con:
            con.execute("DELETE FROM esperas WHERE chat_id = ?", (chat_id,))

    # --- Panel compartido ---------------------------------------------------------------

    def accesos(self) -> list[dict]:
        with self._conexion() as con:
            filas = con.execute("SELECT correo, creado_en FROM accesos ORDER BY creado_en, correo").fetchall()
        return [dict(f) for f in filas]

    def dar_acceso(self, correo: str, creado_en: int) -> None:
        with self._conexion() as con:
            con.execute(
                "INSERT INTO accesos (correo, creado_en) VALUES (?, ?) ON CONFLICT(correo) DO NOTHING",
                (correo, creado_en),
            )

    def quitar_acceso(self, correo: str) -> bool:
        with self._conexion() as con:
            return con.execute("DELETE FROM accesos WHERE correo = ?", (correo,)).rowcount > 0

    def tiene_acceso(self, correo: str) -> bool:
        with self._conexion() as con:
            return con.execute("SELECT 1 FROM accesos WHERE correo = ?", (correo,)).fetchone() is not None

    # --- Palabras aprendidas y ajustes -------------------------------------------------

    def aprender(self, palabra: str, emocion: str) -> None:
        with self._conexion() as con:
            con.execute(
                "INSERT INTO palabras_aprendidas (palabra, emocion) VALUES (?, ?) "
                "ON CONFLICT(palabra) DO UPDATE SET emocion = excluded.emocion",
                (palabra, emocion),
            )

    def aprendidas(self) -> dict[str, str]:
        with self._conexion() as con:
            filas = con.execute("SELECT palabra, emocion FROM palabras_aprendidas").fetchall()
        return {f["palabra"]: f["emocion"] for f in filas}

    def ajuste(self, clave: str) -> str | None:
        with self._conexion() as con:
            fila = con.execute("SELECT valor FROM ajustes WHERE clave = ?", (clave,)).fetchone()
        return fila["valor"] if fila else None

    def guardar_ajuste(self, clave: str, valor: str) -> None:
        with self._conexion() as con:
            con.execute(
                "INSERT INTO ajustes (clave, valor) VALUES (?, ?) "
                "ON CONFLICT(clave) DO UPDATE SET valor = excluded.valor",
                (clave, valor),
            )
